# Description: This playbook is responsible for working with services (started, stopped, restarted, reloaded)
# Reference: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/service_module.html

- hosts:
  remote_user: root
  become: yes
  tasks:
    - name: Install Apache
      yum: 
        name: httpd
        state: installed
    - name: Start Apache service
      service:
        name: httpd
        state: started
        
